layout_spectrum: 0.22200304362922907
typography_spectrum: 0.6826087853405625
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.0013735054526478052
  lightness: 0.9501482034102082
  saturation: 0.9213880475144833
  rhythmicContrast: 0.8639350270386785
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: spark
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Creating extraordinary experiences for corporate and private events worldwide.
description: contact info@sparkfiredance.com now
purpose: []
