typography_spectrum: 0.90046954783611
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4205112310592085
  lightness: 0.07879919046536088
  saturation: 0.9636271726340055
  rhythmicContrast: 0.3059081139508635
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6760805370286107
analytics:
  google: null
  facebook: null
  twitter: null
name: spark
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Creating extraordinary experiences for corporate and private events worldwide.
description: contact info@sparkfiredance.com now
purpose: []
